on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # 0 AM everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install some APT packages
        run: sudo apt install -y git

      - name: Clone target repository
        run: git clone https://github.com/KSXGitHub/pacman-repo.git pacman-repo

      - name: Inspect restored failed build record
        continue-on-error: true
        run: cat pacman-repo/failed-build-records/aur-packages-builder.yaml

      - name: Init AUR Builder
        uses: pacman-repo-builder/action@0.0.0-rc.63
        with:
          command: |
            build-pacman-repo init-aur-builder
            cat build-pacman-repo.yaml

      - name: Build pacman packages
        uses: pacman-repo-builder/action@0.0.0-rc.63
        with:
          command: |
            # cargo-spellcheck depends on hunspell-sys which requires libclang.so
            pacman -S --noconfirm clang

            build-pacman-repo build

      - name: Inspect changed failed build record
        continue-on-error: true
        run: cat pacman-repo/failed-build-records/aur-packages-builder.yaml

      - name: Upload packages
        env:
          COMMIT_AUTHOR_NAME: ${{ secrets.COMMIT_AUTHOR_NAME }}
          COMMIT_AUTHOR_EMAIL: ${{ secrets.COMMIT_AUTHOR_EMAIL }}
          AUTH_USERNAME: KSXGitHub
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
        run: |
          cd pacman-repo
          git config user.name "$COMMIT_AUTHOR_NAME"
          git config user.email "$COMMIT_AUTHOR_EMAIL"
          git add -v .
          git commit -m "Update by $GITHUB_REPOSITORY@$GITHUB_SHA" --allow-empty
          echo "username=$AUTH_USERNAME" >> /tmp/git-login.txt
          echo "password=$AUTH_PASSWORD" >> /tmp/git-login.txt
          echo '#! /bin/bash' >> /tmp/credential-helper
          echo 'cat /tmp/git-login.txt' >> /tmp/credential-helper
          chmod +x /tmp/credential-helper
          git config credential.helper '/tmp/credential-helper'
          git pull origin master --rebase=true # to avoid conflicts due to data races
          git push origin master
